services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
    volumes:
      - '/network-stack/conf/pihole:/etc/pihole'
      - '/network-stack/conf/dnsmasq:/etc/dnsmasq.d'